<form method="post">
    <img class="mb-4 rounded mx-auto d-block" src="img/site/user.png" alt="" width="72" height="72">
    <h1 class="h3 mb-3 fw-normal d-flex justify-content-center">Entrar</h1>

    <div class="form-floating">
        <input type="email" class="form-control" id="floatingInput" name="email" placeholder="name@example.com">
        <label for="floatingInput">Email</label>
    </div>
    <div class="form-floating">
        <input type="password" class="form-control" id="floatingPassword" name="password" placeholder="Password">
        <label for="floatingPassword">Senha</label>
    </div>

    <input class="btn btn-dark w-100 py-2" value="Enviar" type="submit">
    <p class="mt-5 mb-3 text-body-secondary d-flex justify-content-center">&copy; 2017–2023</p>
</form>