<div class="modal modal-sheet position-static d-block bg-body-secondary p-4 py-md-5" tabindex="-1" role="dialog" id="modalChoice">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded-3 shadow">
      <div class="modal-body p-4 text-center">
        <h5 class="mb-0">Usuário Cadastrado com Sucesso!</h5>
        <p class="mb-0">Seja bem-vindo ao Comprai!</p>
      </div>
      <div class="modal-footer flex-nowrap p-0">
        <button type="button" id="button_ok" class="btn btn-lg btn-link fs-6 text-decoration-none col-12 py-3 m-0 rounded-0 border-end"><strong>Ok</strong></button>
      </div>
    </div>
  </div>
</div>